FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# Запускаем dev-сервер Vite с флагом --host, чтобы слушать запросы извне контейнера
CMD ["npm", "run", "dev", "--", "--host"]